version: "3.1"

language: "en"

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 30

policies:
- name: RulePolicy
assistant_id: 20260114-092441-quiet-keyword
